### ISSUE TITLE
Require query-URI == document-URI

### ISSUE THREAD

**Issue by lahmann** [gbv/daiaspec#13]
During the implementation of a VuFind DAIA driver (see https://github.com/vufind-org/vufind/pull/327) capable of querying multiple IDs (as specified in http://gbv.github.io/daiaspec/daia.html#query-api) separated by "|" we came upon the issue that the current DAIA specification is not strict on the relationship between the queried URI and the URI(s) in the response document as some implementations of DAIA services provide a URI for the document-id that differs from the queried URI.

This makes it impossible to identify the documents in the response with the queried IDs. It also implies that any response from a DAIA service contains the availability information for the queried URI even though the response contains a document that does not show any relationship to the queried URI (apart from being the server's response to that queried URI). This disqualifies the DAIA response as an information base for placing holdings etc..

Therefore it is suggested to require that the document id corresponds with the queried URI, identifying the document-element as being the document with the availability information for that specific URI.

**Comment by nichtich** [comment]
Good point, the DAIA server should not return documents that either have a queried id or contain an item with the queried id. I am not sure about support of querying multiple ids:

* how does the client know how many ids are supported?
* what if too many ids are requested?

The latency of querying multiple ids will probably be slower although the total response time may be less. A client could also do many parallel requests. For this reasons I think about dropping the feature. What amount of benefit do you expect from querying multiple ids at once?

**Comment by nichtich** [comment]
Ok, many parallel HTTP requests are bad at least if your client is a browser and you don't use SPDY/HTTP 2, so the multiple id query feature should be kept in DAIA 1.0. Still thinking about the too-many-ids vs ids-not-found issue.

If we require the query id to be included in the response, there is a problem with id normalization: most DAIA servers allow to query with abbreviated URIs.

**Comment by lahmann** [comment]
Thanks for responding to this issue! I have got some comments:

1.) Maximum multiple id queries: we could think about specifying a config or getCapabilities response of the DAIA webservice containing parameters such as maximum multiple id queries etc.. This would be used by the client to build appropriate queries.
Looking at the GBV DAIA webservice there is some (institutional) configuration information available already: http://daia.gbv.de/isil/DE-Hil2/config
Adding a parameter for multiple id queries shouldn't be complicated and being able to retrieve this config information as json/xml using the get parameter `format` would already provide the base functionality.

2.) On the error handling, i.e. handling of too long multiple queries: in my understanding HTTP status 400 (Bad Request) or 413 (Request Entity Too Large) would be appropriate responses for too long queries. If a config file is specified a client could easily read this config as a fallback and adjust its query to the given multiple id query parameter in the config.

3.) Necessity of multiple id queries: of course it also depends on the backend DAIA-ILS how fast multiple id queries are getting processed vs. one query is processed and the result shown while the others are pending (but at least a user might see a response, e.g. with asynchronous request).
But as you pointed out many parallel HTTP requests do have a huge overhead and apart from that web-applications need to be able to do parallel queries as well (e.g. with VuFind2 using the widespread Zend Framework parallel requests are not possible at all - and it's difficult in PHP in general).
I ran some benchmarks (`ab -n 50 'path/to/phpcode/querying/20/documents'`) with multiple id queries vs. single queries using VuFind2 and came up with an increase of factor 5.4 in favour of multiple id queries (390ms vs. 2108ms for 20 ids) - this has especially a deep impact when showing availability for search results as there are usually 20+ availability requests per page. Therefore in my experience having this multiple query feature is essential for using DAIA for live catalogues.

4.) query-URI == document-URI: if I understand the concept of DAIA correctly, a DAIA query asks for a document containing availability information of a record. For each record in an ILS there are multiple DAIA documents holding the availability information for the corresponding record. Each one of these DAIA documents is identified by its URI which puts it into relation to its corresponding record. Therefore if I query a DAIA document identified by an URI I would expect that the DAIA web-service responses with a document that identifies itself as the document I queried - i.e. it has the queried URI as its id.
So, from the perspective of a developer who uses the DAIA API I would assume documents illegal if they'd identify themselves with URIs I didn't query.

**Comment by nichtich** [comment]
1) see #14 

2) a HTTP error code may be appropriate for this case. For not-found documents, however code 404 is difficult if *some* of the queried IDs have been found.

3) ok

4) document URIs are often very long and parts of it can be inferred from the DAIA server`s base URL, so id normalization is an important feature. The DAIA response should include a mapping from queried ids to document ids or documents may have multiple ids (open issue).

**Comment by lahmann** [comment]
1.) thanks, I'll contribute my thoughts in that issue.

2.) You are absolutely right - if some ids aren't found that needs to be handled somehow. If we stick to the document centred approach, i.e. a not found document results in a 404, querying multiple documents could result in either a document containing the documents being found or a 404 if none of the queried ids are found at all. Designing an application that has to handle the availability information would always have to take into account that the result is a 404 - even if that information (no availability information available) should be passed to the user, it would be a very generic "not available". If multiple ids are queried and only for some availability information is returned the same would apply: the application would not find a document having the same id as was queried and therefore it would be assumed that this id has no availability information - hence "not available".
What makes me think this way: I doubt we would gain any relevant information if we would include in a multiple id response e.g. a report, summing up which id was found and which one wasn't. 
On the other hand, if such a report would contain a mapping of query ids and document ids, it could be of some use...
Long story short, I think being agnostic towards the reply as long as the queried id is being found in the response is sufficient for the DAIA use cases I can think of. If we introduce a mapping of query ids to document ids a report/document-map could make the response more explicit (though one would have to think about having such a report returned for every request, even if no document is found).

4.) I agree that some URIs are partially redundant (in combination with the baseurl), but nonetheless URIs identify a specific document with availability information. If the returned document contains another URI as primary identifier, even if this one contains parts of the queried URI, one would have to have knowledge of the id normalization being performed by the DAIA webservice beforehand in order to process the response accordingly. Especially if DAIA APIs would be used for retrieving availability information across several institutions such transformations could become problematic (same applies to open linked data).
Using a mapping could be a solution (see 2.) although I would prefer multiple ids per document to reduce organizational overhead, if requiring that the queried URI identifies the response document is not applicable.

**Comment by dmj** [comment]
Using HTTP 404 as "generic not available" is wrong. DAIA uses HTTP as transport for XML-, JSON- or RDF-encoded messages with availability information. A HTTP 404 has a very specific meaning for HTTP transport: It indicates to the client that the requested resource, i.e. the document with availability information is not available. If you overload the 404 with the semantics from the message-layer then a client can't discriminate between a DAIA webservice that is gone and items that are unavailable.

HTTP 400 for a query that contains more IDs than the server can handle is a different case and okay. The webservice indicates that it can't satisfy the client's query.

**Comment by dmj** [comment]
Re the core of this issue: "we came upon the issue that the current DAIA specification is not strict on the relationship between the queried URI and the URI(s) in the response document as some implementations of DAIA services provide a URI for the document-id that differs from the queried URI."

I don't see why this is a problem that must be solved on the specification level. Did you ask the provider(s) of the mentioned services why they return different document-ids than requested?

**Comment by lahmann** [comment]
>Using HTTP 404 as "generic not available" is wrong.

I might have been a little bit unclear - I absolutely agree that a 404 is reserved for the case that a requested document does not exist (i.e. unrecognised URI). If a document exists and is either available/unavailable this information will be part of the DAIA document (including the message layer). If the webservice is not available the HTTP status code should be a 503.
These three cases are quite clear and distinct from each other.
What I want to suggest in 2.) is to return in multiple id queries only found documents and ignore documents that would have resulted in a 404 if they would have been queried separately.

> I don't see why this is a problem that must be solved on the specification level. Did you ask the provider(s) of the mentioned services why they return different document-ids than requested?

As you can see in https://github.com/vufind-org/vufind/pull/327#issuecomment-86891384 there are cases when it's not possible to alter the configuration of the DAIA webservice. Apart from that a specification for a service provides the common ground every instance of this service shares in order to allow these services to be used by clients that share the same common ground.
Not enforcing any expression of the relationship between the requested document-id and the document-id in the response forces the clients to get hold of external knowledge on how the contacted service will respond. This undermines the common ground the specification ought to provide.
Additionally, keeping the specification not strict in this regard will render queries with multiple ids impossible as the requested ids cannot be mapped to the returned ids.
To be honest I cannot see how this is _not_ a problem that must be solved on the specification level.

**Comment by dmj** [comment]
> I absolutely agree that a 404 is reserved for the case that a requested document does not exist (i.e. unrecognised URI). If a document exists and is either available/unavailable this information will be part of the DAIA document (including the message layer). If the webservice is not available the HTTP status code should be a 503.

1. Consider a DAIA webservice available at http://example.org/daia.php
2. The service provider terminates the service and removes the php file
3. The client requests http://example.org/daia.php?id=gvk:ppn:588923168&format=xml
3. The webserver returns a 404

What does this mean with regards to the availability of gvk:ppn:588923168?

**Comment by nichtich** [comment]
this thread is going offtopic, I created #14 and #15 for two of its aspects.

**Comment by nichtich** [comment]
Thanks a lot for feedback, I included in in the new specification at http://gbv.github.io/daia/
